name: DevSecOps Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Build Docker image
        run: docker build -t my-app .

  sca:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install PyRaider
        run: pip install pyraider

      - name: Run PyRaider scan
        run: pyraider scan my-app

  sast:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit scan
        run: bandit -r my-app

  dast:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install OWASP ZAP
        run: pip install owasp-zap-cli

      - name: Run OWASP ZAP scan
        run: zap-cli -g -u http://localhost:8080 -w report.xml

